import 'package:flutter/material.dart';
import 'package:get/get.dart';

class TextsTrueq{
  static TextsTrueq get to => Get.find();
  final Map<String, Map<String, String>> translations = {
    'es': {
      'titleOnBoarding1': "Explora y encuentra lo que necesitas",
      'titleOnBoarding2': "Dale like y encuentra tu trueque ideal",
      'titleOnBoarding3': "Negocia y cierra el trato",

      'subtitleOnBoarding1': "Descubre artículos subidos por otros usuarios y encuentra el intercambio perfecto.",
      'subtitleOnBoarding2': "Si ambos usuarios están interesados, se generará un match y podrán negociar el intercambio.",
      'subtitleOnBoarding3': "Chatea con el otro usuario y acuerda los detalles del intercambio de forma sencilla y segura.",
      'skip': "Saltar",

      'loginTitle': "Iniciar Sesión",
      'loginSubtitle': "Ingresa con tu correo y contraseña para continuar.",
      'email': "Correo Electrónico",
      'password': "Contraseña",
      'remember': "Recordarme",
      'forgotPassword': "¿Olvidaste tu contraseña?",
      'loginButton': "Iniciar Sesión",
      'noAccount': "¿No tienes cuenta?",
      'registerNow': "Crear cuenta",
      'orContinueWith': "O inicia sesión con",

      'signupTitle': "Crear una cuenta",
      'firstName': "Nombre",
      'lastName': "Apellido",
      'phoneNumber': "Número de Teléfono",
      'emailForm': "Correo Electrónico",
      'username': "Nombre de Usuario",
      'passwordForm': "Contraseña",
      'registerButton': "Registrarse",
      'successMessage': "Registro exitoso",
      'iAgreeTo': "Acepto la",
      'privacyPolicy': "Política de Privacidad",
      'and': "y",
      'termsOfUse': "Términos de uso",
      'orSignUpWith': "O registrate con",

      'confirmEmail': "Verifica tu correo electrónico",
      'confirmSubTitle': "¡Felicidades! Tu cuenta te espera: Verifica tu correo para comenzar a intercambiar y descubrir un mundo de trueques únicos y ofertas personalizadas.",
      'continue': "Continuar",
      'resendEmail': "Reenviar correo",

      'accountCreated': "¡Cuenta creada con éxito!",
      'accountCreatedSubTitle': "¡Empieza a descubrir productos, haz match con otros usuarios y encuentra los mejores trueques!",

      'forgetPasswordTitle': "Contraseña olvidada",
      'forgetPasswordSubTitle': "No te preocupes, puedes restablecer tu contraseña y seguir truequeando sin problemas. Ingresa tu correo y te enviaremos las instrucciones.",
      'submit': "Enviar",

      'changePasswordTitle': "Correo de restablecimiento enviado",
      'changePasswordSubTitle': "Te hemos enviado un correo con un enlace para restablecer tu contraseña. ¡Revisa tu bandeja de entrada!",
      'done': "Hecho",

      'newPassword': "Nueva Contraseña",
      'passwordChanged': "Contraseña cambiada con éxito",
      'changeNewPasswordTitle': "Establecer nueva contraseña",
      'changeNewPasswordSubTitle': "Ingresa una nueva contraseña segura para proteger tu cuenta.",

      'error': "Error",
      'errorLogin': "Correo o contraseña incorrectos",
      'errorTermsAndConditions': "Debes aceptar los términos y condiciones.",
      'errorInsertUser': "No se pudo guardar el usuario",
      'errorNotConfirmedMail': "El email aún no ha sido confirmado.",
      'errorNotConfirmedMail2': "Para continuar debes verificar el email.",
      'verification': "Verificación",
      'sendMailVerification': "Se ha enviado el correo de verificación",
      'resendMailVerification': "Se ha reenviado el correo de verificación.",
      'sendMailPassword': "Se ha enviado un correo para restablecer tu contraseña",
      'resendMailPassword': "Se ha reenviado un correo para restablecer tu contraseña",
      'errorMailNotFound': "No se encontró una cuenta con este correo.",
      'errorTryLater': "Ocurrió un problema al procesar la solicitud. Inténtalo de nuevo más tarde.",
      'errorMailInUse': "El usuario ya existe y está verificado",
      'success': "Éxito",
      'errorFavorite': "No se pudo agregar a favoritos. Intenta de nuevo más tarde.",
      'errorUnfavorite': "No se pudo quitar de favoritos. Intenta de nuevo más tarde.",
      'errorLoadingFavorites': "Hubo un error al cargar tus favoritos. Intenta más tarde.",

      'validatorMailLogin': "Introduce el correo electrónico",
      'validatorPasswordLogin': "Introduce la contraseña",
      'validatorFirstName': "Ingresa tu nombre",
      'validatorLastName': "Ingresa tu apellido",
      'validatorMailSignup': "Ingresa un email válido",
      'validatorUsername': "Ingresa un nombre de usuario",
      'validatorPasswordSignup': "La contraseña debe tener al menos 6 caracteres",

      'home': "Inicio",
      'favourites': "Favoritos",
      'profile': "Perfil",

      'for_you': "Para ti",
      'explore': "Explorar",
      'noProductsAvailable': "No hay productos disponibles.",
      'noAvailableProductsTrueq': 'No tienes productos disponibles para intercambiar.',
      'chooseProductToOffer': '¿Qué producto quieres ofrecer?',

      'usernameNotAvailable': "Nombre de usuario no disponible",
      'emailNotAvailable': "Email no disponible",
      'locationNotAvailable': "Ubicación no disponible",
      'exchanges': "Intercambios:",
      'libraryImage': "Seleccionar foto existente",
      'takePhoto': "Hacer foto",
      'invalidFileType': "Tipo de archivo no permitido",
      'deleteImage': "Eliminar foto actual",
      'myProducts': "Mis Productos",
      'language': "Idioma",
      'changeLanguage': "Cambiar Idioma",
      'selectLanguage': "Seleccionar Idioma",
      'notifications': "Notificaciones",
      'help': "Ayuda",
      'editProfile': 'Editar perfil',

      'available': "Disponible",
      'noProducts': 'No has subido ningún producto todavía.',
      'productEditedSuccessfully': '¡Producto editado con éxito!',

      'category': "Categoría",
      'postedOn': "Publicado el",
      'description': "Descripción",
      'noDescription': "Sin descripción",
      'markAsInterchanged': 'Marcar como intercambiado',
      'markAsAvailable': 'Marcar como disponible',
      'interchanged': 'Intercambiado',
      'couldNotUpdateStatus': 'No se pudo actualizar el estado del producto',
      'viewProfile': 'Ver perfil',
      'startTrueq': "Iniciar Trueq",
      'editProduct': "Editar producto",
      'deleteProduct': "Eliminar producto",
      'confirmDeleteProduct': '¿Eliminar producto?',
      'confirmDeleteMessageProduct': '¿Estás seguro de que quieres eliminar este producto? Esta acción no se puede deshacer.',
      'productDeleted': 'Producto eliminado',
      'productDeletedSuccessfully': 'Tu producto ha sido eliminado correctamente.',

      'location': 'Ubicación',
      'searchLocation': 'Buscar dirección...',
      'locationNotFound': 'No se pudo encontrar esa dirección.',
      'permissionDenied': 'Permiso denegado',
      'locationPermissionExplanation': 'La app necesita acceso a tu ubicación.',
      'permissionDeniedForever': 'Permiso denegado permanentemente',
      'permissionSettingsMessage': 'Habilita los permisos de ubicación desde la configuración del sistema.',
      'currentPosition': 'Tu ubicación',
      'confirmLocation': 'Confirmar ubicación',
      'saveChanges': 'Guardar cambios',
      'changesSaved': 'Cambios guardados correctamente.',

      'enableNotifications': 'Activar notificaciones',
      'enableNotificationsInfo': 'Recibe alertas sobre intercambios, mensajes y novedades.',
      'notificationSettings': 'Configuración de notificaciones',

      'legal': 'Legal',
      'contact': 'Contacto',
      'supportEmail': 'Enviar mensaje a soporte',

      'lastUpdatePrivacy': "Última actualización abril de 2025",
      'privacyPolicyIntro': "En Trueq, respetamos tu privacidad y nos comprometemos a proteger la información personal que compartes con nosotros.",
      'dataRecopilation': "Información que recopilamos",
      'dataRecopilationInfo': "- Información de cuenta (nombre, correo, avatar, etc.)\n- Productos subidos y datos de interacción en la plataforma.\n- Datos de uso para mejorar la experiencia.",
      'dataUsage': "Uso de la información",
      'dataUsageInfo': "Utilizamos tu información para gestionar tu cuenta, mejorar la aplicación, y garantizar la seguridad de Trueq.",
      'contactPolicyInfo': "Si tienes preguntas sobre nuestra política de privacidad, contáctanos a contacto.trueq@gmail.com.",
      'cookieTechnologies': 'Uso de tecnologías',
      'cookieTechnologiesInfo': 'Esta aplicación utiliza servicios de terceros como Google AdMob, Google Maps y otros servicios de Google que pueden recopilar información del dispositivo, como el identificador de publicidad, la ubicación aproximada o datos de uso con fines analíticos y publicitarios. Aunque no se utilizan cookies tradicionales como en los navegadores web, estas tecnologías tienen fines similares. Para más información sobre cómo Google utiliza estos datos, puedes visitar su política de privacidad: ',
      'privacyPolicyGoogle': 'https://policies.google.com/privacy',

      'privacyCookies': 'Política de Cookies',
      'lastUpdateCookies': 'Última actualización abril de 2025',
      'cookiesIntro': 'En Trueq, utilizamos cookies para mejorar la experiencia de usuario, personalizar el contenido y analizar el tráfico en nuestra plataforma.',
      'whatAreCookies': '¿Qué son las cookies?',
      'whatAreCookiesInfo': 'Las cookies son pequeños archivos de texto que los sitios web almacenan en tu dispositivo para guardar información sobre tu visita. Sirven para recordar tus preferencias o para rastrear tu comportamiento mientras navegas por la app.',
      'cookiesTypes': 'Tipos de cookies que utilizamos',
      'cookiesTypesInfo': '- Cookies esenciales: necesarias para el funcionamiento básico de Trueq.\n- Cookies de rendimiento: nos ayudan a comprender cómo interactúan los usuarios con la aplicación.\n- Cookies de personalización: recuerdan tus preferencias para ofrecerte una experiencia más adaptada.',
      'cookiesManagement': 'Gestión de cookies',
      'cookiesManagementInfo': 'Puedes gestionar o desactivar las cookies desde la configuración de tu dispositivo o navegador. No obstante, desactivar algunas cookies puede afectar al funcionamiento de la aplicación.',
      'contactCookiesInfo': 'Si tienes dudas sobre nuestra política de cookies, puedes escribirnos a contacto.trueq@gmail.com',

      'lastUpdateTerms': 'Última actualización abril de 2025',
      'termsIntro': 'Bienvenido a Trueq. Al acceder o utilizar nuestra aplicación, aceptas quedar vinculado por estos Términos de Uso. Estos términos establecen los derechos y obligaciones tanto de los usuarios como de Trueq en relación con el uso de la plataforma. Te recomendamos leerlos detenidamente antes de comenzar a utilizar nuestros servicios. Si no estás de acuerdo con alguna parte de estos términos, por favor no utilices la aplicación. Al continuar, aceptas cumplir con todas las reglas establecidas para mantener un entorno seguro, respetuoso y justo para todos los usuarios.',
      'userResponsibilities': 'Responsabilidades del usuario',
      'userResponsibilitiesInfo': 'El usuario debe proporcionar información veraz y respetar las reglas de intercambio.',
      'prohibitedUses': 'Usos prohibidos',
      'prohibitedUsesInfo': 'Está prohibido usar Trueq para actividades ilegales, ofensivas o que infrinjan derechos de terceros.',
      'modifications': 'Modificaciones de los términos',
      'modificationsInfo': 'Nos reservamos el derecho de modificar estos términos en cualquier momento.',
      'contactTermsInfo': "Si tienes preguntas sobre nuestros términos de uso, contáctanos a contacto.trueq@gmail.com.",

      'legalNotice': 'Aviso Legal',
      'lastUpdateLegal': 'Última actualización abril de 2025',
      'legalIntro': 'Este Aviso Legal regula el uso de la aplicación Trueq, propiedad de Trueq S.L.U.',
      'ownership': 'Titularidad',
      'ownershipInfo': 'Esta app es propiedad de Trueq S.L.U, con CIF X0000000X, y domicilio en Plaza Cortes Valencianas 4-20, Valencia.',
      'responsibility': 'Responsabilidad',
      'responsibilityInfo': 'El titular no se hace responsable del mal uso de la aplicación por parte de los usuarios.',
      'intellectualProperty': 'Propiedad Intelectual',
      'intellectualPropertyInfo': 'Todos los contenidos de esta aplicación están protegidos por derechos de autor y no pueden ser reproducidos sin permiso expreso.',
      'applicableLaw': 'Legislación Aplicable',
      'applicableLawInfo': 'Este aviso legal se rige por la legislación española. Cualquier conflicto se someterá a los tribunales de Madrid.',

      'deleteAccount': "Eliminar cuenta",
      'confirmDeleteUser': '¿Eliminar cuenta?',
      'confirmDeleteMessageUser': '¿Estás seguro de que quieres eliminar tu cuenta? Esta acción no se puede deshacer.',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'accountDeleted': "Cuenta eliminada",
      'accountDeletedSuccess': "Tu cuenta ha sido eliminada correctamente.",
      'logout': "Cerrar sesión",
      'logoutDone': "Sesión cerrada",
      'logoutSuccess': "Has cerrado sesión correctamente.",

      'selectCategory': 'Selecciona una categoría',
      'categoryElectronics': 'Electrónica',
      'categoryFashion': 'Moda',
      'categoryHome': 'Hogar',
      'categorySports': 'Deporte',
      'categoryToys': 'Juguetes',
      'categoryOthers': 'Otros',
      'productTitle': 'Título del producto',
      'productDescription': 'Descripción (opcional)',
      'validatorTitle': 'Introduce un título',
      'imageRequired': 'Debes subir una imagen del producto.',

      'post': 'Publicar',
      'productAddedSuccessfully': '¡Tu producto se ha subido exitosamente!',
      'titleAddTitleProduct': '¿Qué vas a intercambiar?',
      'subtitleAddTitleProduct': 'Ingresa el título del producto',
      'exampleTitle': 'Ejemplo: Zapatillas rojas tamaño 42',

      'chats': "Chats",
      'noChatsYet': "Todavía no tienes chats",
      'chatDisabled': "Este chat está inhabilitado por cambios en los productos",
      'noMessagesChat': "Haz click para empezar la conversación",
      'inactiveChats': "Inactivos",

      'writeMessage': "Escribe un mensaje...",
      'loadingPage': "Cargando...",

      'exploreProducts': "Buscar productos...",

      'exchangesProduct': "intercambios",

      'noFavorites': "No tienes productos en favoritos.",

      'memberSince': "Miembro desde",


    },
    'en': {
      'titleOnBoarding1': "Explore and find what you need",
      'titleOnBoarding2': "Like and find your ideal trade",
      'titleOnBoarding3': "Negotiate and close the deal",

      'subtitleOnBoarding1': "Discover items uploaded by other users and find the perfect exchange.",
      'subtitleOnBoarding2': "If both users are interested, a match will be created and they can negotiate the exchange.",
      'subtitleOnBoarding3': "Chat with the other user and agree on the exchange details easily and securely.",
      'skip': "Skip",

      'loginTitle': "Log In",
      'loginSubtitle': "Enter your email and password to continue.",
      'email': "Email",
      'password': "Password",
      'remember': "Remember Me",
      'forgotPassword': "Forgot your password?",
      'loginButton': "Log In",
      'noAccount': "Don't have an account?",
      'registerNow': "Sign Up",
      'orContinueWith': "Or log in with",

      'signupTitle': "Create an Account",
      'firstName': "First Name",
      'lastName': "Last Name",
      'phoneNumber': "Phone Number",
      'emailForm': "Email",
      'username': "Username",
      'passwordForm': "Password",
      'registerButton': "Sign Up",
      'successMessage': "Registration Successful",
      'iAgreeTo': "I agree to the",
      'privacyPolicy': "Privacy Policy",
      'and': "and",
      'termsOfUse': "Terms of Use",
      'orSignUpWith': "Or sign up with",

      'confirmEmail': "Verify Your Email",
      'confirmSubTitle': "Congratulations! Your account is waiting: Verify your email to start trading and discover a world of unique swaps and personalized deals.",
      'continue': "Continue",
      'resendEmail': "Resend Email",

      'accountCreated': "Account Successfully Created!",
      'accountCreatedSubTitle': "Start discovering products, match with other users, and find the best trades!",

      'forgetPasswordTitle': "Forgot Password",
      'forgetPasswordSubTitle': "Don't worry, you can reset your password and keep trading without issues. Enter your email, and we'll send you instructions.",
      'submit': "Submit",

      'changePasswordTitle': "Password Reset Email Sent",
      'changePasswordSubTitle': "We've sent you an email with a link to reset your password. Check your inbox!",
      'done': "Done",

      'newPassword': "New Password",
      'passwordChanged': "Password Successfully Changed",
      'changeNewPasswordTitle': "Set a New Password",
      'changeNewPasswordSubTitle': "Enter a secure new password to protect your account.",

      'error': "Error",
      'errorLogin': "Incorrect email or password",
      'errorTermsAndConditions': "You must accept the terms and conditions.",
      'errorInsertUser': "User could not be saved",
      'errorNotConfirmedMail': "The email has not been confirmed yet.",
      'errorNotConfirmedMail2': "To continue, you must verify your email.",
      'verification': "Verification",
      'sendMailVerification': "A verification email has been sent",
      'resendMailVerification': "The verification email has been resent.",
      'sendMailPassword': "An email has been sent to reset your password",
      'resendMailPassword': "A password reset email has been resent",
      'errorMailNotFound': "No account found with this email.",
      'errorTryLater': "There was an issue processing the request. Try again later.",
      'errorMailInUse': "The user already exists and is verified",
      'success': "Success",
      'errorFavorite': "Could not add to favorites. Please try again later.",
      'errorUnfavorite': "Could not remove from favorites. Please try again later.",
      'errorLoadingFavorites': "There was an error loading your favorites. Please try again later.",

      'validatorMailLogin': "Enter your email",
      'validatorPasswordLogin': "Enter your password",
      'validatorFirstName': "Enter your first name",
      'validatorLastName': "Enter your last name",
      'validatorMailSignup': "Enter a valid email",
      'validatorUsername': "Enter a username",
      'validatorPasswordSignup': "Password must be at least 6 characters long",

      'home': "Home",
      'favourites': "Favourites",
      'profile': "Profile",

      'for_you': "For you",
      'explore': "Explore",
      'noProductsAvailable': "No products available.",
      'noAvailableProductsTrueq': 'You don’t have any available products to trade.',
      'chooseProductToOffer': 'Which product do you want to offer?',

      'usernameNotAvailable': "Username not available",
      'emailNotAvailable': "Email not available",
      'locationNotAvailable': "Location not available",
      'exchanges': "Exchanges:",
      'libraryImage': "Select an existing",
      'takePhoto': "Take photo",
      'invalidFileType': "Invalid file type",
      'deleteImage': "Delete current photo",
      'myProducts': "My Products",
      'language': "Language",
      'changeLanguage': "Change Language",
      'selectLanguage': "Select Language",
      'notifications': "Notifications",
      'help': "Help",
      'editProfile': 'Edit Profile',

      'available': "Available",
      'noProducts': 'You haven’t uploaded any products yet.',
      'productEditedSuccessfully': 'Product edited successfully!',

      'category': "Category",
      'postedOn': "Posted on",
      'description': "Description",
      'noDescription': "No description",
      'markAsInterchanged': 'Mark as interchanged',
      'markAsAvailable': 'Mark as available',
      'interchanged': 'Interchanged',
      'couldNotUpdateStatus': 'Could not update the product status',
      'viewProfile': 'View profile',
      'editProduct': "Edit product",
      'deleteProduct': "Delete product",
      'startTrueq': "Start Trueq",

      'location': 'Location',
      'searchLocation': 'Search address...',
      'locationNotFound': 'Could not find that address.',
      'permissionDenied': 'Permission denied',
      'locationPermissionExplanation': 'The app needs access to your location.',
      'permissionDeniedForever': 'Permission permanently denied',
      'permissionSettingsMessage': 'Enable location permissions from the system settings.',
      'currentPosition': 'Your location',
      'confirmLocation': 'Confirm location',
      'saveChanges': 'Save changes',
      'changesSaved': 'Changes saved successfully.',

      'enableNotifications': 'Enable notifications',
      'enableNotificationsInfo': 'Receive alerts about exchanges, messages, and updates.',
      'notificationSettings': 'Notification settings',

      'legal': 'Legal',
      'contact': 'Contact',
      'supportEmail': 'Send message to support',

      'lastUpdatePrivacy': "Last update April 2025",
      'privacyPolicyIntro': "At Trueq, we respect your privacy and are committed to protecting the personal information you share with us.",
      'dataRecopilation': "Information we collect",
      'dataRecopilationInfo': "- Account information (name, email, avatar, etc.)\n- Uploaded products and interaction data on the platform.\n- Usage data to improve the experience.",
      'dataUsage': "Data usage",
      'dataUsageInfo': "We use your information to manage your account, improve the app, and ensure the security of Trueq.",
      'contactPolicyInfo': "If you have questions about our privacy policy, contact us at contacto.trueq@gmail.com.",
      'cookieTechnologies': 'Use of Technologies',
      'cookieTechnologiesInfo': 'This app uses third-party services such as Google AdMob, Google Maps, and other Google services that may collect device information, such as the advertising identifier, approximate location, or usage data for analytics and advertising purposes. Although traditional cookies like those used in web browsers are not employed, these technologies serve similar purposes. For more information on how Google uses this data, you can visit their privacy policy:',
      'privacyPolicyGoogle': 'https://policies.google.com/privacy',

      'privacyCookies': 'Cookies Policy',
      'lastUpdateCookies': 'Last update April 2025',
      'cookiesIntro': 'At Trueq, we use cookies to enhance user experience, personalize content, and analyze traffic on our platform.',
      'whatAreCookies': 'What are cookies?',
      'whatAreCookiesInfo': 'Cookies are small text files that websites store on your device to save information about your visit. They help remember your preferences or track your behavior as you browse the app.',
      'cookiesTypes': 'Types of cookies we use',
      'cookiesTypesInfo': '- Essential cookies: necessary for the basic operation of Trueq.\n- Performance cookies: help us understand how users interact with the app.\n- Personalization cookies: remember your preferences to offer you a more tailored experience.',
      'cookiesManagement': 'Cookie management',
      'cookiesManagementInfo': 'You can manage or disable cookies from your device or browser settings. However, disabling some cookies may affect the functioning of the app.',
      'contactCookies': 'Contact',
      'contactCookiesInfo': 'If you have questions about our cookie policy, you can write to us at contacto.trueq@gmail.com',

      'lastUpdateTerms': 'Last update April 2025',
      'termsIntro': 'Welcome to Trueq. By accessing or using our app, you agree to be bound by these Terms of Use. These terms outline the rights and obligations of both users and Trueq regarding the use of the platform. We recommend reading them carefully before you start using our services. If you do not agree with any part of these terms, please do not use the app. By continuing, you agree to comply with all the rules established to maintain a safe, respectful, and fair environment for all users.',
      'userResponsibilities': 'User responsibilities',
      'userResponsibilitiesInfo': 'The user must provide truthful information and follow the exchange rules.',
      'prohibitedUses': 'Prohibited uses',
      'prohibitedUsesInfo': 'It is prohibited to use Trueq for illegal, offensive activities, or activities that infringe on third-party rights.',
      'modifications': 'Modifications to the terms',
      'modificationsInfo': 'We reserve the right to modify these terms at any time.',
      'contactTermsInfo': 'If you have questions about our terms of use, contact us at contacto.trueq@gmail.com',

      'legalNotice': 'Legal Notice',
      'lastUpdateLegal': 'Last update April 2025',
      'legalIntro': 'This Legal Notice governs the use of the Trueq app, owned by Trueq S.L.U.',
      'ownership': 'Ownership',
      'ownershipInfo': 'This app is owned by Trueq S.L.U, with CIF X0000000X, and located at Plaza Cortes Valencianas 4-20, Valencia.',
      'responsibility': 'Responsibility',
      'responsibilityInfo': 'The owner is not responsible for the misuse of the app by users.',
      'intellectualProperty': 'Intellectual Property',
      'intellectualPropertyInfo': 'All content in this app is protected by copyright and may not be reproduced without explicit permission.',
      'applicableLaw': 'Applicable Law',
      'applicableLawInfo': 'This legal notice is governed by Spanish law. Any disputes will be subject to the courts of Madrid.',

      'deleteAccount': 'Delete account',
      'confirmDeleteUser': 'Delete account?',
      'confirmDeleteMessageUser': 'Are you sure you want to delete your account? This action cannot be undone.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'accountDeleted': "Account deleted",
      'accountDeletedSuccess': "Your account has been successfully deleted.",
      'logout': "Log out",
      'logoutDone': "Logged out",
      'logoutSuccess': "You have successfully logged out.",

      'selectCategory': 'Select a category',
      'categoryElectronics': 'Electronics',
      'categoryFashion': 'Fashion',
      'categoryHome': 'Home',
      'categorySports': 'Sports',
      'categoryToys': 'Toys',
      'categoryOthers': 'Others',
      'productTitle': 'Product title',
      'productDescription': 'Description (optional)',
      'validatorTitle': 'Enter a title',
      'imageRequired': 'You must upload a product image.',

      'post': 'Post',
      'productAddedSuccessfully': 'Your product has been successfully uploaded!',
      'titleAddTitleProduct': 'What are you going to trade?',
      'subtitleAddTitleProduct': 'Enter the product title',
      'exampleTitle': 'Example: Red sneakers size 42',

      'chats': "Chats",
      'noChatsYet': "You don't have any chats yet",
      'chatDisabled': "This chat is disabled due to changes in the products",
      'noMessagesChat': 'Tap to start the conversation',
      'inactiveChats': "Inactive",

      'writeMessage': "Type a message...",
      'loadingPage': "Loading...",

      'exploreProducts': "Search products...",

      'exchangesProduct': "exchanges",

      'noFavorites': "You have no products in favorites.",

      'memberSince': "Member since",
    }

  };

  String getText(String key) {
    String locale = Get.locale?.languageCode ?? 'es';
    return translations[locale]?[key] ?? key;
  }

  void changeLanguage(String languageCode) {
    Locale locale = Locale(languageCode);
    Get.updateLocale(locale);
  }
}